# Generated by Django 4.0.4 on 2022-06-12 02:44

from django.db import migrations, models
import django_countries.fields
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('formato', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='portadadiscos')),
                ('tracklist', django_quill.fields.QuillField()),
            ],
        ),
    ]
