# Generated by Django 4.0.4 on 2022-06-12 04:43

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Title', models.CharField(max_length=200)),
                ('video_Body', models.TextField()),
                ('video_Video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
    ]
