# Generated by Django 4.0.4 on 2022-06-12 17:07

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0006_author_category_post_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorias',
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publicado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='resumen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.autor'),
            preserve_default=False,
        ),
    ]
