# Generated by Django 4.0.4 on 2022-06-12 17:11

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_autor_rename_category_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=django_quill.fields.QuillField(),
        ),
    ]
