# Generated by Django 4.0.4 on 2022-06-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_remove_post_publicado_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, unique_for_month=True),
        ),
    ]
