# Generated by Django 4.0.4 on 2022-06-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_alter_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_Body',
            new_name='video_cuerpo',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_Title',
            new_name='video_titulo',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_Video',
            new_name='video_video',
        ),
    ]
