# Generated by Django 4.0.4 on 2022-06-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_rename_content_disco_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_cuerpo',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='videoplayer',
            old_name='video_video',
            new_name='video',
        ),
    ]
