# Generated by Django 4.0.4 on 2022-06-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_rename_video_cuerpo_videoplayer_cuerpo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoPlayer',
            new_name='Videos',
        ),
    ]
