# Generated by Django 4.0.4 on 2022-06-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_rename_videoplayer_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
